/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(data_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b669ea6cf8efb4e5ab10529acded9d52) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora_sdr/data_source.h>
// pydoc.h is automatically generated in the build directory
#include <data_source_pydoc.h>

void bind_data_source(py::module &m) {

  using data_source = ::gr::lora_sdr::data_source;

  py::class_<data_source, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<data_source>>(m, "data_source", D(data_source))

      .def(py::init(&data_source::make), py::arg("pay_len"),
           py::arg("n_frames"), D(data_source, make))

      ;
}
