/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(deinterleaver.h) */
/* BINDTOOL_HEADER_FILE_HASH(65d663d2dd00415de5989550a4b1fb3e) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora_sdr/deinterleaver.h>
// pydoc.h is automatically generated in the build directory
#include <deinterleaver_pydoc.h>

void bind_deinterleaver(py::module &m) {

  using deinterleaver = ::gr::lora_sdr::deinterleaver;

  py::class_<deinterleaver, gr::block, gr::basic_block,
             std::shared_ptr<deinterleaver>>(m, "deinterleaver",
                                             D(deinterleaver))

      .def(py::init(&deinterleaver::make), py::arg("soft_decoding"),
           D(deinterleaver, make))

      ;
}
