/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(gray_mapping.h) */
/* BINDTOOL_HEADER_FILE_HASH(42acb0b27196fd81600dab69004410d4) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora_sdr/gray_mapping.h>
// pydoc.h is automatically generated in the build directory
#include <gray_mapping_pydoc.h>

void bind_gray_mapping(py::module &m) {

  using gray_mapping = ::gr::lora_sdr::gray_mapping;

  py::class_<gray_mapping, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<gray_mapping>>(m, "gray_mapping", D(gray_mapping))

      .def(py::init(&gray_mapping::make), py::arg("soft_decoding"),
           D(gray_mapping, make))

      ;
}
