/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(msg_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(540881050992bd163dafc3514d5bce8d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora_sdr/msg_sink.h>
// pydoc.h is automatically generated in the build directory
#include <msg_sink_pydoc.h>

void bind_msg_sink(py::module& m)
{

    using msg_sink    = ::gr::lora_sdr::msg_sink;


    py::class_<msg_sink, gr::block, gr::basic_block,
        std::shared_ptr<msg_sink>>(m, "msg_sink", D(msg_sink))

        .def(py::init(&msg_sink::make),
           py::arg("filename"),
           D(msg_sink,make)
        )
        



        ;




}








