/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(whiteningt.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d9f4f7c63398fcd1c07a993fcc38174b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora_sdr/whiteningt.h>
// pydoc.h is automatically generated in the build directory
#include <whiteningt_pydoc.h>

void bind_whiteningt(py::module& m)
{

    using whiteningt    = gr::lora_sdr::whiteningt;


    py::class_<whiteningt, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<whiteningt>>(m, "whiteningt", D(whiteningt))

        .def(py::init(&whiteningt::make),
           D(whiteningt,make)
        )
        



        ;




}








