@startuml
state "Tx" as Tx1
state "Tx" as Tx2





state c <<choice>>

Tx1 --> c
Tx2 --> c



state StreamingRecviever{
    state "Rx" as Rx1
    state "Rx" as Rx2
    state "Rx" as Rx3
    state "Rx" as Rx4
    state "Rx" as Rx5
    state "Rx" as Rx6

    Rx1 : sf = 7
    Rx2 : sf = 8
    Rx3 : sf = 9
    Rx4 : sf = 10
    Rx5 : sf = 11
    Rx6 : sf = 12
}
c --> StreamingRecviever

StreamingRecviever --> Rx1
StreamingRecviever --> Rx2
StreamingRecviever --> Rx3
StreamingRecviever --> Rx4
StreamingRecviever --> Rx5
StreamingRecviever --> Rx6


@enduml