/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(data_source_sim.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(df301d07c23fc6029217e47d2b109add)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora_sdr/data_source_sim.h>
// pydoc.h is automatically generated in the build directory
#include <data_source_sim_pydoc.h>

void bind_data_source_sim(py::module& m)
{

    using data_source_sim    = ::gr::lora_sdr::data_source_sim;


    py::class_<data_source_sim, gr::block, gr::basic_block,
        std::shared_ptr<data_source_sim>>(m, "data_source_sim", D(data_source_sim))

        .def(py::init(&data_source_sim::make),
           py::arg("pay_len"),
           py::arg("n_frames"),
           py::arg("string_input"),
           py::arg("mean"),
           py::arg("exit_control"),
           D(data_source_sim,make)
        )
        



        ;




}








