/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_src.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e15183f8de170c5492b05677a74fd26f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora_sdr/frame_src.h>
// pydoc.h is automatically generated in the build directory
#include <frame_src_pydoc.h>

void bind_frame_src(py::module& m)
{

    using frame_src    = ::gr::lora_sdr::frame_src;


    py::class_<frame_src, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<frame_src>>(m, "frame_src", D(frame_src))

        .def(py::init(&frame_src::make),
           py::arg("sf"),
           py::arg("pay_len"),
           py::arg("delay"),
           py::arg("offset"),
           py::arg("cfo"),
           py::arg("n_frames"),
           py::arg("os_factor"),
           py::arg("rand_sto"),
           D(frame_src,make)
        )
        



        ;




}








