/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_detector_timeout.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(995c94c17918b85937b9e17c30aadf44)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora_sdr/frame_detector_timeout.h>
// pydoc.h is automatically generated in the build directory
#include <frame_detector_timeout_pydoc.h>

void bind_frame_detector_timeout(py::module& m)
{

    using frame_detector_timeout    = ::gr::lora_sdr::frame_detector_timeout;


    py::class_<frame_detector_timeout, gr::block, gr::basic_block,
        std::shared_ptr<frame_detector_timeout>>(m, "frame_detector_timeout", D(frame_detector_timeout))

        .def(py::init(&frame_detector_timeout::make),
           py::arg("sf"),
           py::arg("samp_rate"),
           py::arg("bw"),
           py::arg("n_bytes"),
           py::arg("detect_second_packet"),
           D(frame_detector_timeout,make)
        )
        



        ;




}








