/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(header.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d5eebc74dfad2b8961fac7203890cd5f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora_sdr/header.h>
// pydoc.h is automatically generated in the build directory
#include <header_pydoc.h>

void bind_header(py::module& m)
{

    using header    = ::gr::lora_sdr::header;


    py::class_<header, gr::block, gr::basic_block,
        std::shared_ptr<header>>(m, "header", D(header))

        .def(py::init(&header::make),
           py::arg("impl_head"),
           py::arg("has_crc"),
           py::arg("cr"),
           D(header,make)
        )
        



        ;




}








