/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mu_detection.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e2917f22ae703474f3e07fa8da198fb7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora_sdr/mu_detection.h>
// pydoc.h is automatically generated in the build directory
#include <mu_detection_pydoc.h>

void bind_mu_detection(py::module& m)
{

    using mu_detection    = ::gr::lora_sdr::mu_detection;


    py::class_<mu_detection, gr::block, gr::basic_block,
        std::shared_ptr<mu_detection>>(m, "mu_detection", D(mu_detection))

        .def(py::init(&mu_detection::make),
           py::arg("sf"),
           py::arg("os_factor"),
           py::arg("snr_threshold"),
           D(mu_detection,make)
        )
        



        ;




}








