/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mu_synchro.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(610d46276927e3c2eaca8722e6b675c5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora_sdr/mu_synchro.h>
// pydoc.h is automatically generated in the build directory
#include <mu_synchro_pydoc.h>

void bind_mu_synchro(py::module& m)
{

    using mu_synchro    = ::gr::lora_sdr::mu_synchro;


    py::class_<mu_synchro, gr::block, gr::basic_block,
        std::shared_ptr<mu_synchro>>(m, "mu_synchro", D(mu_synchro))

        .def(py::init(&mu_synchro::make),
           py::arg("sf"),
           py::arg("os_factor"),
           py::arg("len"),
           D(mu_synchro,make)
        )
        



        ;




}








