/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(noise_est.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ab49b16d3fe8784d90898525040ed7d6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora_sdr/noise_est.h>
// pydoc.h is automatically generated in the build directory
#include <noise_est_pydoc.h>

void bind_noise_est(py::module& m)
{

    using noise_est    = ::gr::lora_sdr::noise_est;


    py::class_<noise_est, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<noise_est>>(m, "noise_est", D(noise_est))

        .def(py::init(&noise_est::make),
           py::arg("n_samples"),
           D(noise_est,make)
        )
        



        ;




}








