/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(signal_detector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(aea2f8831d1d7b7e851376111939afa0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora_sdr/signal_detector.h>
// pydoc.h is automatically generated in the build directory
#include <signal_detector_pydoc.h>

void bind_signal_detector(py::module& m)
{

    using signal_detector    = ::gr::lora_sdr::signal_detector;


    py::class_<signal_detector, gr::block, gr::basic_block,
        std::shared_ptr<signal_detector>>(m, "signal_detector", D(signal_detector))

        .def(py::init(&signal_detector::make),
           py::arg("sf"),
           py::arg("os_factor"),
           py::arg("threshold"),
           py::arg("margin"),
           py::arg("fft_symb"),
           py::arg("transp_len"),
           D(signal_detector,make)
        )
        



        ;




}








