/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-lora_sdr
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_LORA_SDR_API_H
#define INCLUDED_LORA_SDR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_lora_sdr_EXPORTS
#define LORA_SDR_API __GR_ATTR_EXPORT
#else
#define LORA_SDR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_LORA_SDR_API_H */
