@startuml
skinparam componentStyle rectangle

package Tx {
  package FrameSync [
    - pay_len
    - bw
    - sf
    - samp_rate
  ]
  package FFTDemod [
    - impl_head
    - bw
    - sf
    - samp_rate
    ]
  package Deinterleaver [
    - sf
  ]

  package HeaderDecoder [
    - impl_head
    - cr
    - pay_len
    - has_crc
  ]


  [FrameSync] -> [FFTDemod]
  [FFTDemod] -> [GrayDemap]
  [GrayDemap] -> [Deinterleaver]
  [Deinterleaver] -> [HammingDecoder]
  [HammingDecoder] -> [HeaderDecoder]
  [HeaderDecoder] -> [Dewhitening]
  [Dewhitening] -> [CrcVerify]
}

@enduml