@startuml
skinparam componentStyle rectangle

package Tx {
  package DataSource [
    - pay_len
    - n_frame
    - string_input
  ]
  package AddHeader [
    - impl_head
    - has_crc
    - cr
  ]
  package AddCrc [
    - has_crc
  ]
  package HammingEncoding [
    - cr
    - sf
  ]
  package Interleaver [
    - cr
    - sf
  ]
  package GrayMapping [
    - sf
  ]
  package Modulate [
    - sf
    - samp_rate
    - bw
  ]



  [DataSource] -> [Whitening]
  [Whitening] -> [AddHeader]
  [AddHeader] -> [AddCrc]
  [AddCrc] -> [HammingEncoding]
  [HammingEncoding] -> [Interleaver]
  [Interleaver] -> [GrayMapping]
  [GrayMapping] -> [Modulate]
}

@enduml